AllCops:
  TargetRubyVersion: 2.1

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'pyr.gemspec'
    - 'spec/**/*'
    - 'Rakefile'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
